name: Main

on:
  push:
    branches:
      - main
    tags:
      - '*'

  pull_request:

env:
  REGISTRY: europe-north1-maven.pkg.dev/artifact-registry-5n/barnevern-maven
  ARTIFACT_REVISION: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || format('{0}-SNAPSHOT', github.ref_name) }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - id: "auth"
        name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v2.1.2"
        with:
          workload_identity_provider: "projects/848539402404/locations/global/workloadIdentityPools/gh-actions/providers/gh-actions"
          service_account: "gh-actions-barnevern@artifact-registry-5n.iam.gserviceaccount.com"
          token_format: "access_token"

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: "${{ runner.os }}-gradle-${{ github.sha }}"
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew -Dsonar.token=${{ secrets.SONAR_TOKEN }} build jacocoTestReport sonar --build-cache --info

#      - name: Deploy artifact to Google artifact registry
#        if: ${{ startsWith(github.ref, 'refs/tags/') }}
#        run: ./gradlew -Pversion=${{ env.ARTIFACT_REVISION }} publish  --info
