name: Main

on:
  push:
    branches:
      - main
    tags:
      - '*'

  pull_request:

env:
  ARTIFACT_REVISION: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || format('{0}-SNAPSHOT', github.ref_name) }}
  SONAR_PARAMS: ${{ secrets.SONAR_TOKEN && format('jacocoTestReport sonar -Dsonar.token={0}', secrets.SONAR_TOKEN) || '' }}

jobs:
  build_artifact_and_push:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - id: "auth"
        name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v2.1.8"
        with:
          workload_identity_provider: "projects/${{ secrets.GAR_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/gh-actions/providers/gh-actions"
          service_account: "gh-actions-barnevern@${{ secrets.GAR_PROJECT_ID }}.iam.gserviceaccount.com"
          token_format: "access_token"

      - name: Build with Gradle
        uses: burrunan/gradle-cache-action@v2
        with:
          gradle-build-scan-report: false
          concurrent: true
          gradle-distribution-sha-256-sum-warning: false
          gradle-version: wrapper
          arguments: |
            check
            ${{ env.SONAR_PARAMS }} 
            --daemon --parallel --build-cache --info            

      - name: Deploy artifact to Google artifact registry
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: ./gradlew -Pversion=${{ env.ARTIFACT_REVISION }} publish --build-cache --info
