name: Main

on:
  push:
    branches:
      - main
    tags:
      - '*'

  pull_request:

jobs:
  build:
    uses: statisticsnorway/barn-maven-parent/.github/workflows/build-artifact-and-push.yml@main
    secrets: inherit